POST http://127.0.0.1:5000/gg/add
Content-Type: application/json

{
      "name" : "salut ",
        "deliveryAddress" : "comment",
        "contact" : "bien",
        "active" : 1
}

###
POST http://127.0.0.1:2000/order/add 
Content-Type : application/json 

{ 
   "createDate" : "2022-01-01",
   "customerId" : 1 
}